[project]
name = "ttable"
version = "0.1.0"
description = "Terminal Based timetable"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "prompt-toolkit>=3.0.52",
    "requests>=2.32.5",
    "rich>=14.2.0",
]
